"""
=========================================================
ASV Manager
Konstanten
=========================================================
"""

# Tabellen

SHEET_GAMES = "ICS2"
SHEET_HISTORY = "HISTORY"
SHEET_MEMBERS = "MITGLIEDER"
SHEET_TEAMS = "MANNSCHAFTEN"
SHEET_TEAM_VEREINE = "TEAM_VEREINE"
SHEET_TEAM_TRAINER = "TEAM_TRAINER"


# Spiel-Spalten

COL_GAME_ID = "GAME_ID"
COL_STATUS = "STATUS"
COL_LIGA = "LIGA"
COL_DATUM = "DATUM"
COL_STARTZEIT = "STARTZEIT"
COL_ENDZEIT = "ENDZEIT"
COL_GEGNER = "GEGNER"
COL_ORT = "ORT"
COL_TYP = "TYP"
COL_ART = "ART"
COL_BESCHREIBUNG = "BESCHREIBUNG"
COL_MEMBER_ID = "MEMBER_ID"
COL_VORNAME = "VORNAME"
COL_NACHNAME = "NACHNAME"
COL_GEBURTSDATUM = "GEBURTSDATUM"
COL_EINTRITT = "EINTRITT"
COL_AUSTRITT = "AUSTRITT"
COL_BEMERKUNG = "BEMERKUNG"
# Mannschaften
COL_TEAM_ID = "TEAM_ID"
COL_SAISON = "SAISON"
COL_MANNSCHAFT = "MANNSCHAFT"
COL_TYP = "TYP"
COL_AKTIV = "AKTIV"
COL_LEADVEREIN = "LEADVEREIN"
COL_VEREIN = "VEREIN"
COL_ROLLE = "ROLLE"